development: &default_options
  appoptics_key: 851970940f4420e767d092e0c8fc4b4ffcc3d89ffa8cbbe42fdaf14d473efe32
  google_project_id: task-206011
  oauth2:
    client_id: [YOUR_CLIENT_ID]
    client_secret: [YOUR_CLIENT_SECRET]
